export enum GRAPHTYPE {
    GRAPH = 'GRAPH',
    ANALYTICGRAPH = 'ANALYTICGRAPH',
    DENSETRAJECTORY = 'DENSETRAJECTORY',
    SKETCH = 'SKETCH',
    LINE = 'LINE',
    ARC = 'ARC',
    CIRCLE = 'CIRCLE',
    BEZIER = 'BEZIER',
    QUADRATIC_BEZIER = 'QUADRATIC_BEZIER',
    CUBIC_BEZIER = 'CUBIC_BEZIER',
    COMBINED_GRAPH = 'COMBINED_GRAPH',
    POLYGON = 'POLYGON',
    TRIANGLE = 'TRIANGLE',
    QUADRILATERAL = 'QUADRILATERAL',
    RECTANGLE = 'RECTANGLE',
    REGULAR_POLYGON = 'REGULAR_POLYGON',
    ROUNDED_RECT = 'ROUNDED_RECT',
    COMPLEX_GRAPH = 'COMPLEX_GRAPH',
    MAGNIFYING_GLASS = 'MAGNIFYING_GLASS',
    IMAGE = 'IMAGE',
    VIDEO = 'VIDEO',
    TEXTS = 'TEXTS',
    TEXTPARAGRAPH = 'TEXTPARAGRAPH',
    TEXTELEMENT = 'TEXTELEMENT',
    PRINTABLE_TEXTELEMENT = 'PRINTABLE_TEXTELEMENT',
    NONPRINTABLE_TEXTELEMENT = 'NONPRINTABLE_TEXTELEMENT',
    TEXTFIELDS = 'TEXTFIELDS',
}

// 视图类型 —— 字符串联合，业务层可通过 `type` 字段自定义扩展类型
export type ViewType = string

export const VIEWTYPE = {
    VIEW: 'VIEW',
    TEXTVIEW: 'TEXTVIEW',
    GRAPHVIEW: 'GRAPHVIEW',
    IMAGEVIEW: 'IMAGEVIEW',
    VIDEOVIEW: 'VIDEOVIEW',
    COMBINEDVIEW: 'COMBINEDVIEW',
    FLEXVIEW: 'FLEXVIEW',
    SELECTBOXVIEW: 'SELECTBOXVIEW',
    INPUT: 'INPUT',
    EDITABLETEXT: 'EDITABLETEXT',
} as const

// 数学类型枚举
export enum MATHTYPE {
    POINT3 = 'POINT3',
    VECTOR3 = 'VECTOR3',
    MATRIX4 = 'MATRIX4',
    BOUNDS = 'BOUNDS',
}

// 样式类型枚举
export enum STYLETYPE {
    COLOR = 'COLOR',
    GRADIENT = 'GRADIENT',
    IMAGE_PATTERN = 'IMAGE_PATTERN',
    VIDEO_PATTERN = 'VIDEO_PATTERN',
    FILL_STYLE = 'FILL_STYLE',
    STROKE_STYLE = 'STROKE_STYLE',
    SHADOW_STYLE = 'SHADOW_STYLE',
    STYLE = 'STYLE',
}

// 场景类型枚举
export enum SCENETYPE {
    SCENE = 'SCENE',
}

// 相机类型枚举
export enum CAMERATYPE {
    BASE = 'BASE_CAMERA',
    ORTHOGRAPHIC = 'ORTHOGRAPHIC_CAMERA',
    PERSPECTIVE = 'PERSPECTIVE_CAMERA',
}

// 插件类型枚举
export enum ADDONTYPE {
    BOUNDING_BOX = 'BOUNDING_BOX',
    VERTEX = 'VERTEX',
    BOX_DECORATION = 'BOX_DECORATION',
}

// 文字对齐方式枚举
export enum VERTICALALIGN {
    TOP = 'TOP',
    MIDDLE = 'MIDDLE',
    BOTTOM = 'BOTTOM',
}

export enum HORIZONTALALIGN {
    LEFT = 'LEFT',
    CENTER = 'CENTER',
    RIGHT = 'RIGHT',
}

// 字体样式枚举
export enum FontStyle {
    NORMAL = 'normal',
    ITALIC = 'italic',
    OBLIQUE = 'oblique',
}

// 字体粗细枚举
export enum FontWeight {
    NORMAL = 'normal',
    BOLD = 'bold',
    BOLDER = 'bolder',
    LIGHTER = 'lighter',
    WEIGHT_100 = '100',
    WEIGHT_200 = '200',
    WEIGHT_300 = '300',
    WEIGHT_400 = '400',
    WEIGHT_500 = '500',
    WEIGHT_600 = '600',
    WEIGHT_700 = '700',
    WEIGHT_800 = '800',
    WEIGHT_900 = '900',
}
